# Generated by Django 3.0.4 on 2020-03-09 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0005_auto_20200309_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 14, 45, 13, 252507, tzinfo=utc)),
        ),
    ]
